### ISSUE TITLE
Error with "push    large dword ptr fs:0"

### ISSUE THREAD

**Issue by erseal** [programa-stic/barf-project#2]
Error occurred while processing "push    large dword ptr fs:0" and "mov     large fs:0, ecx" in develop and impove branches

Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
  File "/home/user/barf-project-develop/barf/barf/core/reil/reil.py", line 282, in __str__
    operands_str = ", ".join(map(print_oprnd, self._operands))
  File "/home/user/barf-project-develop/barf/barf/core/reil/reil.py", line 259, in print_oprnd
    size_str = str(oprnd.size) if oprnd.size else ""
AttributeError: 'NoneType' object has no attribute 'size'
Logged from file x86translator.py, line 287
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    for addr, asm_instr, reil_instrs in barf.translate(ea_start, ea_end):
  File "/home/user/barf-project-develop/barf/barf/barf.py", line 179, in translate
    yield addr, asm, self.ir_translator.translate(asm)
  File "/home/user/barf-project-develop/barf/barf/arch/x86/x86translator.py", line 282, in translate
    check_operands_size(instr, self._arch_info.architecture_size)
  File "/home/user/barf-project-develop/barf/barf/arch/x86/x86translator.py", line 162, in check_operands_size
    assert instr.operands[0].size == arch_size, \
AttributeError: 'NoneType' object has no attribute 'size'

**Comment by cnheitman** [comment]
Hi! I pushed a fix for this in the ``develop`` branch. Please, check it.

**Comment by erseal** [comment]
thanks!
