### ISSUE TITLE
Exception: Error loading ELF file

### ISSUE THREAD

**Issue by sh4m2hwz** [programa-stic/barf-project#58]
>>> barf = BARF("/home/user/code")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/barf-0.6.0-py3.8.egg/barf/barf.py", line 90, in __init__
    self.open(filename)
  File "/usr/local/lib/python3.8/dist-packages/barf-0.6.0-py3.8.egg/barf/barf.py", line 211, in open
    self.binary = BinaryFile(filename)
  File "/usr/local/lib/python3.8/dist-packages/barf-0.6.0-py3.8.egg/barf/core/binary.py", line 160, in __init__
    self._open(filename)
  File "/usr/local/lib/python3.8/dist-packages/barf-0.6.0-py3.8.egg/barf/core/binary.py", line 229, in _open
    self._open_elf(filename)
  File "/usr/local/lib/python3.8/dist-packages/barf-0.6.0-py3.8.egg/barf/core/binary.py", line 279, in _open_elf
    raise Exception("Error loading ELF file.")
Exception: Error loading ELF file.
>>> 
code:
https://pastebin.com/HeRaWfUc

**Comment by luisdonin** [comment]
Hi, I'm facing a similar problem, have you found a solution?
