### ISSUE TITLE
BARF fails to disassemble /bin/ls

### ISSUE THREAD

**Issue by neuromancer** [programa-stic/barf-project#7]
Using recover_cfg.py to disassemble /bin/ls fails:

    [+] Recovering program CFG...
    Traceback (most recent call last):
    File "./recover_cfg.py", line 28, in <module>
      cfg = barf.recover_cfg()
    File "/home/g/Codigo/barf-project/barf/barf/barf.py", line 294, in recover_cfg
      bb_list = self.bb_builder.build(start_addr, end_addr)
    File "/home/g/Codigo/barf-project/barf/barf/analysis/basicblock/basicblock.py", line 368, in build 
      bbs = self._find_candidate_bbs(start_address, end_address)
    File "/home/g/Codigo/barf-project/barf/barf/analysis/basicblock/basicblock.py", line 426, in _find_candidate_bbs
      bb = self._disassemble_bb(curr_addr, end_address + 0x1)
    File "/home/g/Codigo/barf-project/barf/barf/analysis/basicblock/basicblock.py", line 553, in _disassemble_bb
      ir = self._ir_trans.translate(asm)
    File "/home/g/Codigo/barf-project/barf/barf/arch/x86/x86translator.py", line 304, in translate 
      check_operands_size(instr, self._arch_info.architecture_size)
    File "/home/g/Codigo/barf-project/barf/barf/arch/x86/x86translator.py", line 193, in check_operands_size
    "Invalid operands size: %s" % instr
      AssertionError: Invalid operands size: stm   [QWORD rdi, EMPTY, DWORD t2999]

where /bin/ls is a  ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=64d095bc6589dd4bfbf1c6d62ae985385965461b, stripped

**Comment by cnheitman** [comment]
Done. Fix in commit 28014c3e651b3ec558c87d2deb9ff854914737cb.
